Fix compiler warnings with NHOP code
ipdk-io/krnlmon pull request #14
Opened 2022-12-08 18:34 UTC by n-sandeep

Signed-off-by: Sandeep N <sandeep.nagapattinam@intel.com>

2022-12-08 18:47 UTC, nupuruttarwar approved these changes
LGTM

2022-12-08 18:55 UTC, ffoulkes commented on switchapi/switch_nhop_int.h
> +    (void)(_tmp_nhop_group_info == *_info);                         \
I don't understand. `(_tmp_nhop_group_info == *_info)` is a Boolean expression. Why are we casting a `bool` to `void`?

2022-12-10 16:00 UTC, ffoulkes requested changes

2022-12-10 16:00 UTC, ffoulkes commented on switchapi/switch_nhop_int.h
> +    (void)(_tmp_nhop_group_info == *_info);                         \
May I suggest the following?
```
#define switch_nhop_get_group(_device, _handle, _info)                    \
    switch_handle_get(                                              \
        _device, SWITCH_HANDLE_TYPE_NHOP_GROUP, _handle, (void **)(_info))
```

2022-12-18 23:07 UTC, ffoulkes commented
Superseded by PR #20.

2022-12-18 23:07 UTC, closed without merging